# Generated by Django 5.1.3 on 2024-11-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarefa_ordemapresentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nomeTarefa',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='ordemApresentacao',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
